uploads = []

[[generated]]
id = "cpCWB_eM5fwRUQTWpFsMA"
uri = "file://artifacts/winvesty-app/assets/images/icon.png"
type = "image"
title = "winvesty_app_icon"

[[outputs]]
id = "FrjLoOQUnDxiULrus7uj3"
uri = "file://winvesty-qr.png"
type = "image"
title = "QR Code Winvesty — Expo Go"
