kind = "mobile"
previewPath = "/"
title = "Winvesty App"
version = "1.0.0"
id = "artifacts/winvesty-app"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 25250

[services.development]
run = "pnpm --filter @workspace/winvesty-app run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/winvesty-app", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/winvesty-app", "run", "serve" ]

[services.env]
PORT = "25250"
BASE_PATH = "/"
